### ISSUE TITLE
forking?

### ISSUE THREAD

**Issue by DocMAX** [termux/termux-services#25]
my run file looks like this:

```
#!/data/data/com.termux/files/usr/bin/sh
exec proot-distro login archlinux --user docmax --shared-tmp --bind /storage/emulated/0:/mnt/sdcard -- sh -c 'DISPLAY=:0 exec dbus-launch xfce4-session'
```

when i try to stop with "sv down vncserver" the service is still running. i think it's because sv is not aware of the processes anymore. can this be fixed?

**Comment by sylirre** [comment]
It doesn't work because signal is sent by sv to the parent process. However `proot` never exits until main process was not finished.

Technically you can force kill the PRoot using the `sv kill servicename` but this can make things even worse as won't kill process group properly.

The command like
```
for p in $(pgrep -f proot-distro); do pkill -TERM -P "$p"; done
```
properly terminates the PRoot environment.

Runit (Termux Services) is not a good thing for launching PRoot Distro. The reason is that it designed to be used for one process per service. This is why actually you have to start command with `exec`.

Termux:Widget or some shell scripts (even few functions in .bashrc) would be better suitable for starting & stopping PRoot Distro with desktop.

**Comment by DocMAX** [comment]
Well, thank you for the detailed explanation. After thinking i came to my own solution.
This is whats in my run script now. sv down xfce4 shuts down the session properly:
```
#!/data/data/com.termux/files/usr/bin/sh

cleanup() {
    pkill xfce4-session
    exit 0
}

trap cleanup TERM
proot-distro login archlinux --user docmax --shared-tmp --bind /storage/emulated/0:/mnt/sdcard -- sh -c 'DISPLAY=:0 dbus-launch xfce4-session' &
wait
```

Pretty cool, isn't it?
