### ISSUE TITLE
how to add self service

### ISSUE THREAD

**Issue by foxundermoon** [termux/termux-services#4]

**Comment by Grimler91** [comment]
What do you mean with self service? 

If you want to create a script for controlling some non-supported program then you need to run something like: 
```
cd $PREFIX/var/service
mkdir -p @YOUR-PROGRAM@/log
echo '#!/bin/sh' > sshd/run
echo 'exec @YOUR-PROGRAM@ 2>&1' >> @YOUR-PROGRAM@/run
chmod +x @YOUR-PROGRAM@/run
touch @YOUR-PROGRAM@/down
ln -sf $PREFIX/share/termux-services/svlogger @YOUR-PROGRAM@/log/run
```

`@YOUR-PROGRAM@` needs to be replaced with the name of your program. 
The `echo 'exec @YOUR-PROGRAM@ 2>&1' >> @YOUR-PROGRAM@/run` might need to be customized, the program has to be run in the foreground and output everything to stdout. http://smarden.org/runit/runscripts.html has a lot of scripts for various programs.

We set this up in our build.sh scripts, so see for example here for openssh: https://github.com/termux/termux-packages/blob/53de8cdd264228255c02388f30c38f90d3f9eab2/packages/openssh/build.sh#L87

See also the wiki page https://wiki.termux.com/wiki/Termux-services

**Comment by foxundermoon** [comment]
good . 
thx

**Comment by atikattar1104** [comment]
~Hi @Grimler91 ,~ 

~I Actually Created A Simple Bash Script, Based On The Snippet You Provided Above. This Is My 1st Time Working With Code Made By Others, And I Thought It Would Be Better To Let You Know About This.~

~I Have Uploaded It To A Private Repo On My Profile, And Sent You The Invite To It, So That You Can See The Code. It Only Contains One File Tho, As Of Now.~

~Thanks.~ 

NVM, I Already Created One Long Time Ago Using Man Pages And Runit's Own Documentations.
